### ISSUE TITLE
Dead link: http://documentation.chartiq.com/tutorial-Data%20Loading.html

### ISSUE THREAD

**Issue by jasonmcleod** [ChartIQ/Charting-Library---Angular-Seed-Project#14]
Working through the following error after importing my copy of ChartIQ:

```ChartUI.html:42 ERROR TypeError: CIQ.QuoteFeed.Demo is not a constructor```

The following link results in a 404
```link: http://documentation.chartiq.com/tutorial-Data%20Loading.html```

Referenced here
https://github.com/ChartIQ/Charting-Library---Angular-Seed-Project/blob/6527e973f27a6f0e983e0cd412ba967adbfac63f/src/app/chart_service/chart.service.ts#L8

**Comment by RMcNeely** [comment]
Thanks for letting us know, that tutorial has moved to [this address](http://documentation.chartiq.com/tutorial-DataIntegrationOverview.html). Let us know if you need any help integrating your quoteFeed with the library.

**Comment by RMcNeely** [comment]
With your library you should either have one of two files, `quoteFeedSamples.js` or `quoteFeedSimulator.js` to get you started. By default we import `quoteFeedSamples` which contains the constructor for CIQ.QuoteFeed.Demo. If you don't have this file add the script tag for quoteFeedSimulator and replace the quoteFeed that the chart attaches.  This file should be replaced with a quoteFeed of your own which provides market data for production. If you have any questions about integrating a quoteFeed please reach out to us at dev@chartiq.com

**Comment by jasonmcleod** [comment]
Thanks for the quick reply! I ended up getting everything working. Found an example on jsfiddle and worked it in. Will update this thread when I am back at my machine for anyone else following along.
