### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by adventmedia** [ChartIQ/Charting-Library---Angular-Seed-Project#18]
webpack fails to compile:
ERROR in [at-loader] ./src/app/chart_service/chart.service.ts:2:21 
    TS2306: File '/Users/andrewmacrae/Documents/Charting-Library---Angular-Seed-Project-master/src/chartiq_library/js/quoteFeedSimulator.js' is not a module.

**Comment by jdrichards50** [comment]
@adventmedia, could you please submit your issue to our support? Email dev@chartiq.com.
