### ISSUE TITLE
import a plugin

### ISSUE THREAD

**Issue by adventmedia** [ChartIQ/Charting-Library---Angular-Seed-Project#19]

**Comment by adventmedia** [comment]
How does one import a plugin - specifically, the cryptoIQ plugin?

**Comment by RMcNeely** [comment]
The cyrptoIQ plugin is designed to work with the web components that go with the sample templates. They can be imported like any other module if you include all of their dependencies however they will not work out of the box as Angular components.
```typscript
import * as _exports from '../../chartiq_library/js/chartiq';
import '../../chartiq_library/js/componentUI'
import '../../chartiq_library/js/thirdparty/splines'
import '../../chartiq_library/js/cryptoiq'```
