### ISSUE TITLE
Browser throws error from chartiq internal scripts. 

### ISSUE THREAD

**Issue by DeeNeon** [ChartIQ/Charting-Library---Angular-Seed-Project#24]
You can see below expiration date has no relation with this error. 
This has already been sent to your support team as well, but in case someone else is experiencing this should be also aware when it's fixed.
 
<img width="1440" alt="screen shot 2019-01-14 at 8 08 56 am" src="https://user-images.githubusercontent.com/2610038/51128735-d6311000-17e5-11e9-8ae7-f51eead3f1f2.png">

Cheers.

**Comment by RMcNeely** [comment]
For future reference: this is a known issue with 6.2.2, please contact support or an account manger to upgrade.
